GET http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3000/tasks/7a55e8c8-e2e5-4b26-abec-6afee0a59fc0 HTTP/1.1
Content-Type: application/json

###
POST http://localhost:3000/tasks HTTP/1.1
Content-Type: application/json

{
  "name": "test"
}

###
DELETE http://localhost:3000/tasks/14284584-1430-472a-88df-4c58d6e9eb8b HTTP/1.1
Content-Type: application/json

###
PATCH http://localhost:3000/tasks/7a55e8c8-e2e5-4b26-abec-6afee0a59fc0 HTTP/1.1
Content-Type: application/json

{
  "name": "test - updated"
}